server:
  port: 8080
spring:
  application:
    name: reggie
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # springboot与swagger兼容

mybatis:
  configuration:
    map-underscore-to-camel-case: true
